apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: xchar
  namespace: crossbell
  annotations:
    avp.kubernetes.io/path: "kv/data/crossbell/xchar"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`<DOMAIN>`)
      services:
        - name: xchar
          port: 3000
