apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xchar-image
  namespace: crossbell
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
  storageClassName: standard-rwm
